/* FreeSchoolEducation - Concept lessons
 * Provides the "Learn the concept" section for every skill: a plain-language
 * explanation, a worked example, a key rule, and corner-case cards that cover
 * the tricky situations. Keyed by skill.type (math) or by keyword (MCQ topics).
 */
(function (global) {
  "use strict";

  // ---- Math concepts, keyed by skill.type --------------------------------
  const BY_TYPE = {
    count: {
      title: "Counting and number sense",
      means: "Counting tells how many objects are in a group. Say one number for each object, in order, without skipping or repeating.",
      example: "5 dots counted one at a time \u2014 1, 2, 3, 4, 5 \u2014 is 5.",
      remember: "The last number you say is the total for the whole group.",
      cases: [["Count once each", "Touch or mark every object once so you never count it twice."],
        ["Start at one", "Begin at 1 unless a problem tells you to count on from another number."],
        ["Zero means none", "If there are no objects, the count is 0."]],
    },
    compare: {
      title: "Comparing numbers",
      means: "Comparing decides which number is greater, which is smaller, or whether they are equal. Line the numbers up and check place value from the left.",
      example: "498,201 > 489,999 because 9 ten-thousands beats 8 ten-thousands.",
      remember: "The symbol's open side always faces the greater number: > and <.",
      cases: [["Same length", "Compare digit by digit from the left; stop at the first place that differs."],
        ["Different length", "For whole numbers, more digits usually means a greater number."],
        ["Equal values", "If every place matches, the numbers are equal (=)."]],
    },
    order: {
      title: "Ordering numbers",
      means: "Ordering arranges numbers from least to greatest (or greatest to least) by comparing them two at a time.",
      example: "12, 27, 34, 41 in order from least to greatest.",
      remember: "Least to greatest goes up; greatest to least goes down.",
      cases: [["Find the smallest first", "Pick the least number, then the next, and so on."],
        ["Watch place value", "A longer whole number is usually larger."],
        ["Equal numbers", "Equal numbers can go in either order next to each other."]],
    },
    add: {
      title: "Addition",
      means: "Addition combines amounts. Line up digits by place value so ones are under ones and tens under tens, then regroup when a column reaches ten.",
      example: "4,786 + 2,549: 6 + 9 = 15 ones, so write 5 and carry 1 ten. The sum is 7,335.",
      remember: "Regroup (carry) whenever a column adds to 10 or more.",
      cases: [["Regroup once", "6 + 9 = 15, so write 5 and carry 1 ten."],
        ["No regrouping", "5,321 + 2,146 needs no carrying because no column reaches ten."],
        ["Add three numbers", "Add two numbers first, then add the third to that total."]],
    },
    add3: {
      title: "Adding three numbers",
      means: "Add three numbers by combining two of them first, then adding the third to that subtotal.",
      example: "8 + 7 + 5: 8 + 7 = 15, then 15 + 5 = 20.",
      remember: "Order does not change the sum \u2014 add the easy pair first.",
      cases: [["Make ten", "Pair numbers that make 10 to add faster (7 + 3 first)."],
        ["Any order", "3 + 8 + 7 equals 8 + 7 + 3; the total stays the same."],
        ["Regroup as needed", "Carry whenever the running total passes a ten."]],
    },
    sub: {
      title: "Subtraction",
      means: "Subtraction takes one amount away from another. Line up place values and regroup (borrow) when the top digit is too small.",
      example: "5,003 \u2212 1,478: borrow across the zeros first, giving 3,525.",
      remember: "Check subtraction by adding the answer to the number you took away.",
      cases: [["No regrouping", "687 \u2212 254 subtracts each column directly."],
        ["Regroup once", "72 \u2212 8: borrow 1 ten so 12 \u2212 8 = 4."],
        ["Across zeros", "5,003 \u2212 1,478 must borrow through the zeros from the thousands."]],
    },
    mul: {
      title: "Multiplication",
      means: "Multiplication is a fast way to add equal groups. An area model splits a factor into tens and ones, multiplies each part, then adds.",
      example: "23 \u00D7 4 = (20 \u00D7 4) + (3 \u00D7 4) = 80 + 12 = 92.",
      remember: "Order does not matter: 3 \u00D7 4 = 4 \u00D7 3.",
      cases: [["Turn it around", "3 \u00D7 4 and 4 \u00D7 3 both equal 12."],
        ["Break apart", "24 \u00D7 13 = (24 \u00D7 10) + (24 \u00D7 3) = 240 + 72 = 312."],
        ["Multiply by zero", "Any number times 0 is 0."]],
    },
    div: {
      title: "Division",
      means: "Division shares a total into equal groups. The dividend is shared, the divisor is the number of groups, and the quotient is the amount in each group.",
      example: "84 \u00F7 6 = 14 means 84 objects make 6 equal groups of 14.",
      remember: "Check with divisor \u00D7 quotient = dividend. A remainder is always smaller than the divisor.",
      cases: [["Shares evenly", "84 \u00F7 6 = 14 with nothing left over."],
        ["Leftover pieces", "85 \u00F7 6 = 14 remainder 1."],
        ["Check by multiplying", "6 \u00D7 14 = 84 proves the quotient is right."]],
    },
    place: {
      title: "Place value",
      means: "A digit's place tells its value. In 582,641 the 8 sits in the ten-thousands place, so it means 80,000, not 8.",
      example: "Moving a 6 from the hundreds place to the thousands place changes its value from 600 to 6,000.",
      remember: "Each step left is 10 times greater; each step right is 10 times smaller.",
      cases: [["Zero as placeholder", "In 305,072 the 0 in the thousands place holds the spot so other digits keep their value."],
        ["Compare same length", "For 45,210 and 45,120, the first place that differs decides: 2 hundreds beats 1 hundred."],
        ["Say it in words", "642,908 is six hundred forty-two thousand, nine hundred eight."]],
    },
    round: {
      title: "Rounding",
      means: "Rounding gives a nearby, friendly number for estimating. Find the place you are rounding to, then look at the digit immediately to its right.",
      example: "386,749 to the nearest thousand is 387,000 because the hundreds digit is 7.",
      remember: "5 or more rounds up; 4 or less stays down.",
      cases: [["Round down", "386,499 to the nearest thousand is 386,000 (hundreds digit 4)."],
        ["Round up", "386,749 to the nearest thousand is 387,000 (hundreds digit 7)."],
        ["Exact 5 and carry", "386,500 rounds up to 387,000; a 9 that carries can roll into the next place."]],
    },
    "frac-add": {
      title: "Adding fractions",
      means: "Fractions add when the denominators match, because the pieces are the same size. Add only the numerators and keep the denominator.",
      example: "3/8 + 2/8 = 5/8.",
      remember: "Never add the denominators \u2014 they name the size of each piece.",
      cases: [["Like denominators", "3/8 + 2/8 = 5/8."],
        ["Past one whole", "5/6 + 3/6 = 8/6 = 1 1/3."],
        ["Simplify the result", "2/8 + 2/8 = 4/8 = 1/2."]],
    },
    "frac-sub": {
      title: "Subtracting fractions",
      means: "Fractions with matching denominators subtract by taking away the numerators. The denominator stays the same.",
      example: "7/10 \u2212 3/10 = 4/10, which simplifies to 2/5.",
      remember: "Simplify the final fraction when the top and bottom share a factor.",
      cases: [["Like denominators", "7/10 \u2212 3/10 = 4/10 = 2/5."],
        ["From one whole", "1 \u2212 3/8 = 8/8 \u2212 3/8 = 5/8."],
        ["Simplify", "4/10 shares a factor of 2, so it becomes 2/5."]],
    },
    percent: {
      title: "Percent of a number",
      means: "A percent is a part out of 100. To find a percent of a number, write the percent as a fraction or decimal, then multiply.",
      example: "25% of 80 = 0.25 \u00D7 80 = 20.",
      remember: "50% is half, 25% is a quarter, 10% is one tenth.",
      cases: [["Friendly percents", "10% of 200 is 20; just move the decimal one place."],
        ["Half and quarter", "50% of 60 = 30; 25% of 60 = 15."],
        ["More than 100%", "150% of 40 = 60, which is larger than the original."]],
    },
    "int-add": {
      title: "Adding and subtracting integers",
      means: "Integers include negatives, zero, and positives. On a number line, adding a positive moves right and adding a negative moves left.",
      example: "-8 + 3 = -5, because you start at -8 and move 3 steps right.",
      remember: "Same signs add and keep the sign; different signs subtract and take the bigger number's sign.",
      cases: [["Same signs", "-4 + -6 = -10."],
        ["Different signs", "-9 + 5 = -4; subtract and keep the larger size's sign."],
        ["Subtracting a negative", "3 \u2212 (-6) = 3 + 6 = 9."]],
    },
    "int-mul": {
      title: "Multiplying and dividing integers",
      means: "When multiplying or dividing integers, the sign of the answer depends only on how many negative signs are used.",
      example: "-7 \u00D7 (-3) = 21, because two negatives make a positive.",
      remember: "Two same signs make positive; two different signs make negative.",
      cases: [["Negative \u00D7 negative", "-4 \u00D7 -5 = 20 (positive)."],
        ["Negative \u00D7 positive", "-6 \u00D7 3 = -18 (negative)."],
        ["Zero", "Any integer times 0 is 0."]],
    },
    abs: {
      title: "Absolute value",
      means: "Absolute value is a number's distance from zero on the number line, so it is never negative.",
      example: "|-5| = 5 because -5 is five steps away from zero.",
      remember: "The bars mean distance, not a negative sign.",
      cases: [["Negative input", "|-5| = 5."], ["Positive input", "|5| = 5."], ["Zero", "|0| = 0."]],
    },
    eval: {
      title: "Evaluating expressions",
      means: "To evaluate an expression, substitute the value for the variable, then follow the order of operations (parentheses, multiply/divide, add/subtract).",
      example: "Evaluate 3x + 4 when x = 5: 3 \u00D7 5 + 4 = 19.",
      remember: "Multiply before you add, unless parentheses say otherwise.",
      cases: [["Multiply first", "2 + 3 \u00D7 4 = 2 + 12 = 14."],
        ["Parentheses first", "(2 + 3) \u00D7 4 = 20."],
        ["Substitute carefully", "Replace every copy of the variable with its value."]],
    },
    linear: {
      title: "One-step equations",
      means: "An equation says two sides are equal. Solve by doing the inverse operation to both sides to get the variable alone.",
      example: "x + 7 = 12 \u2192 subtract 7 from both sides \u2192 x = 5.",
      remember: "Whatever you do to one side, do to the other side too.",
      cases: [["Undo addition", "x + 7 = 12 \u2192 x = 5."],
        ["Undo subtraction", "x \u2212 4 = 9 \u2192 x = 13."],
        ["Check your answer", "Put the value back in to confirm both sides match."]],
    },
    linear2: {
      title: "Two-step equations",
      means: "A two-step equation needs two inverse operations. Undo addition or subtraction first, then undo multiplication or division.",
      example: "3x + 5 = 20 \u2192 subtract 5 \u2192 3x = 15 \u2192 divide by 3 \u2192 x = 5.",
      remember: "Reverse the order of operations: undo +/\u2212 before \u00D7/\u00F7.",
      cases: [["Subtract then divide", "3x + 5 = 20 \u2192 x = 5."],
        ["Add then divide", "2x \u2212 6 = 8 \u2192 2x = 14 \u2192 x = 7."],
        ["Negative coefficient", "-2x + 1 = 9 \u2192 -2x = 8 \u2192 x = -4."]],
    },
    slope: {
      title: "Slope of a line",
      means: "Slope measures steepness as rise over run \u2014 the change in y divided by the change in x between two points.",
      example: "Through (1, 2) and (4, 8): slope = (8 \u2212 2)/(4 \u2212 1) = 6/3 = 2.",
      remember: "Subtract the coordinates in the same order on top and bottom.",
      cases: [["Positive slope", "The line rises from left to right."],
        ["Negative slope", "The line falls; the rise is negative."],
        ["Zero slope", "A flat, horizontal line has slope 0."]],
    },
    power: {
      title: "Exponents",
      means: "An exponent tells how many times to multiply the base by itself.",
      example: "2^4 = 2 \u00D7 2 \u00D7 2 \u00D7 2 = 16.",
      remember: "The exponent is a count of factors, not a multiplier.",
      cases: [["Small powers", "3^2 = 9."],
        ["Power of one", "Any number to the 1st power is itself."],
        ["Power of zero", "Any nonzero number to the 0 power is 1."]],
    },
    quadratic: {
      title: "Solving quadratics",
      means: "A quadratic involves a squared variable. Simple quadratics like x\u00B2 = k are solved by taking the square root of both sides.",
      example: "x\u00B2 = 49 \u2192 x = 7 (positive root).",
      remember: "Squaring hides a sign: x\u00B2 = 49 has roots 7 and -7.",
      cases: [["Perfect squares", "x\u00B2 = 25 \u2192 x = 5."],
        ["Two roots", "x\u00B2 = 9 has solutions 3 and -3."],
        ["Estimate", "If k is not a perfect square, the root is between whole numbers."]],
    },
    area: {
      title: "Area of rectangles",
      means: "Area is the flat space inside a shape, measured in square units. A rectangle's area is length \u00D7 width.",
      example: "A 6 by 4 rectangle covers 6 \u00D7 4 = 24 square units.",
      remember: "Area uses square units; perimeter uses regular units.",
      cases: [["Rectangle", "6 \u00D7 4 = 24 square units."],
        ["Square", "Side 5 gives 5 \u00D7 5 = 25 square units."],
        ["Missing side", "Area 24 with length 6 means width 24 \u00F7 6 = 4."]],
    },
    perimeter: {
      title: "Perimeter",
      means: "Perimeter is the distance all the way around a shape. Add every side length.",
      example: "A 6 by 4 rectangle: 6 + 4 + 6 + 4 = 20 units.",
      remember: "Walk around the shape once and count every side.",
      cases: [["Add all sides", "6 + 4 + 6 + 4 = 20."],
        ["Square shortcut", "Side 5 gives 4 \u00D7 5 = 20."],
        ["Irregular shape", "Add every side, even the short ones."]],
    },
    "area-tri": {
      title: "Area of triangles",
      means: "A triangle's area is half the base times the height. The height is the straight-up distance to the top point.",
      example: "Base 10, height 6: \u00BD \u00D7 10 \u00D7 6 = 30 square units.",
      remember: "Do not forget the \u00BD \u2014 a triangle is half of a rectangle.",
      cases: [["Standard", "\u00BD \u00D7 8 \u00D7 5 = 20."],
        ["Height is not a side", "Use the perpendicular height, not a slanted edge."],
        ["Odd product", "If base \u00D7 height is odd, the area ends in .5."]],
    },
    circle: {
      title: "Circumference of circles",
      means: "Circumference is the distance around a circle. It equals 2\u03C0r, where r is the radius.",
      example: "Radius 5: 2 \u00D7 3.14 \u00D7 5 = 31.4.",
      remember: "Use the radius for 2\u03C0r, or the diameter for \u03C0d.",
      cases: [["From radius", "2\u03C0r with r = 5 is about 31.4."],
        ["From diameter", "\u03C0d with d = 10 is also about 31.4."],
        ["Use \u03C0 \u2248 3.14", "Round at the end for a clean answer."]],
    },
    volume: {
      title: "Volume of prisms",
      means: "Volume counts the cubic units that fill a solid. A rectangular prism's volume is length \u00D7 width \u00D7 height.",
      example: "4 \u00D7 3 \u00D7 2 = 24 cubic units.",
      remember: "Volume uses three measurements and cubic units.",
      cases: [["Multiply three", "4 \u00D7 3 \u00D7 2 = 24."],
        ["Layers", "A layer of 12 cubes with 2 layers is 24."],
        ["Missing dimension", "Volume 24 with base 12 means height 24 \u00F7 12 = 2."]],
    },
    mean: {
      title: "Mean, median, and mode",
      means: "The mean is the average: add the values and divide by how many there are. The median is the middle value in order; the mode appears most often.",
      example: "Mean of 4, 8, 6, 2: (4 + 8 + 6 + 2) \u00F7 4 = 5.",
      remember: "Sort the numbers before finding the median.",
      cases: [["Mean", "Add all values, then divide by the count."],
        ["Median", "Put values in order and take the middle one."],
        ["Mode", "The value that shows up most often; there may be none or several."]],
    },
    pythagorean: {
      title: "Pythagorean theorem",
      means: "In a right triangle, the square of the hypotenuse equals the sum of the squares of the legs: a\u00B2 + b\u00B2 = c\u00B2.",
      example: "Legs 3 and 4: \u221A(3\u00B2 + 4\u00B2) = \u221A25 = 5.",
      remember: "The hypotenuse is always the longest side, opposite the right angle.",
      cases: [["Common triple", "3, 4, 5 is a right triangle."],
        ["Scaled triple", "6, 8, 10 works too (double 3-4-5)."],
        ["Find a leg", "If c and one leg are known, subtract to find the other leg's square."]],
    },
  };

  // ---- MCQ concepts, matched by keyword in the skill name ----------------
  const BY_KEYWORD = {
    "synonym": { title: "Synonyms", means: "Synonyms are words with the same or nearly the same meaning. Swapping one for the other keeps the sentence's meaning.", example: "happy and joyful are synonyms.", remember: "Synonyms match meaning, not spelling.", cases: [["Shades of meaning", "big and huge are synonyms, but huge is stronger."], ["Same part of speech", "Replace a verb with a verb, a noun with a noun."], ["Context matters", "bright can mean shiny or smart depending on the sentence."]] },
    "antonym": { title: "Antonyms", means: "Antonyms are words with opposite meanings.", example: "hot and cold are antonyms.", remember: "An antonym reverses the meaning of a word.", cases: [["Direct opposites", "up/down, in/out."], ["Prefix opposites", "happy/unhappy use a prefix to flip meaning."], ["Not a synonym", "warm is not the antonym of hot \u2014 cold is."]] },
    "rhym": { title: "Rhyming words", means: "Rhyming words end with the same sound.", example: "cat and hat rhyme.", remember: "Rhyme is about ending sound, not spelling.", cases: [["Same ending sound", "tree and bee rhyme."], ["Different spelling", "blue and shoe rhyme even though they look different."], ["Near misses", "cat and cap do not rhyme."]] },
    "letter": { title: "Letters", means: "Letters make the sounds of words. Vowels are a, e, i, o, u; the rest are consonants.", example: "The letter after C is D.", remember: "Know the alphabet order and which letters are vowels.", cases: [["Vowels", "a, e, i, o, u (and sometimes y)."], ["Order", "Letters follow a set order: A, B, C, D..."], ["Upper and lower", "A and a are the same letter."]] },
    "beginning sound": { title: "Beginning sounds", means: "The beginning sound is the first sound you hear in a word.", example: "ball begins with the /b/ sound.", remember: "Listen to the first sound, not just the first letter.", cases: [["Single sounds", "sun starts with /s/."], ["Blends", "star starts with the /st/ blend."], ["Match by sound", "phone starts with /f/, not /p/."]] },
    "noun": { title: "Nouns", means: "A noun names a person, place, thing, or idea.", example: "In 'The bright star shines,' star is the noun.", remember: "Nouns can often follow the words a, an, or the.", cases: [["Person or place", "teacher, city."], ["Thing or idea", "book, freedom."], ["Not an action", "run is a verb, not a noun."]] },
    "verb": { title: "Verbs", means: "A verb shows an action or a state of being.", example: "In 'She reads a book,' reads is the verb.", remember: "If you can do it, it is probably a verb.", cases: [["Action verbs", "jump, read, build."], ["Being verbs", "is, are, was."], ["Not a noun", "table is a noun, not a verb."]] },
    "root": { title: "Greek and Latin roots", means: "A root is the core part of a word that carries its basic meaning. Knowing roots helps you unlock new words.", example: "The root bio- means life, as in biology.", remember: "Break a long word into its root and affixes to find meaning.", cases: [["bio = life", "biography, biology."], ["tele = far", "telephone, television."], ["port = carry", "transport, portable."]] },
    "main idea": { title: "Main idea", means: "The main idea is what a passage is mostly about \u2014 the big point, not a small detail.", example: "A passage about how bees help plants has the main idea 'bees help plants grow.'", remember: "The main idea is supported by the details, not the other way around.", cases: [["Whole passage", "It covers the entire text, not one sentence."], ["Not a detail", "A single fact is a detail, not the main idea."], ["Often near the top", "Look at the first or last sentence for clues."]] },
    "ecosystem": { title: "Ecosystems", means: "An ecosystem is a community of living things interacting with each other and their non-living environment, such as soil, water, and sunlight.", example: "In a pond, plants, fish, insects, and water all interact as one ecosystem.", remember: "Everything is connected \u2014 a change to one part affects the others.", cases: [["Producers", "Plants make their own food using sunlight."], ["Consumers", "Animals get energy by eating plants or other animals."], ["Decomposers", "Fungi and bacteria break down dead material and recycle nutrients."]] },
    "adaptation": { title: "Adaptations", means: "An adaptation is a trait that helps a living thing survive and reproduce in its environment.", example: "A polar bear's thick fur is an adaptation to the cold.", remember: "Adaptations develop over many generations, not in one lifetime.", cases: [["Body features", "A cactus stores water to survive the desert."], ["Behaviors", "Birds migrate to find food and warmth."], ["Camouflage", "Coloring that helps an animal blend in and hide."]] },
    "food chain": { title: "Food chains", means: "A food chain shows how energy moves from one living thing to another as they eat and are eaten.", example: "Grass \u2192 grasshopper \u2192 frog \u2192 snake \u2192 hawk.", remember: "Arrows point toward the living thing that receives the energy.", cases: [["Producers first", "The chain begins with a plant that captures sunlight."], ["Consumers", "Each animal passes energy to the next."], ["Balance", "Removing one link affects the whole chain."]] },
    "matter": { title: "States of matter", means: "Matter is anything that has mass and takes up space. Its common states are solid, liquid, and gas.", example: "Water is a solid (ice), a liquid (water), and a gas (vapor).", remember: "Heating and cooling change the state, not the kind of matter.", cases: [["Solid", "Keeps its shape and volume."], ["Liquid", "Takes the shape of its container but keeps its volume."], ["Gas", "Spreads to fill its whole container."]] },
    "force": { title: "Forces and motion", means: "A force is a push or a pull that can change an object's motion. Bigger forces cause bigger changes.", example: "Kicking a ball applies a force that makes it move.", remember: "Balanced forces cause no change; unbalanced forces change motion.", cases: [["Gravity", "Pulls objects toward Earth."], ["Friction", "Slows objects that rub against a surface."], ["Applied force", "A direct push or pull you give an object."]] },
    "energy": { title: "Energy", means: "Energy is the ability to do work or cause change. It comes in forms like light, heat, sound, and motion.", example: "A moving bike has kinetic energy; a stretched rubber band has potential energy.", remember: "Energy can change form but is not created or destroyed.", cases: [["Kinetic", "The energy of motion."], ["Potential", "Stored energy waiting to be used."], ["Transfer", "Energy moves between objects and forms."]] },
    "genetic": { title: "Genetics", means: "Genetics is the study of how traits pass from parents to offspring through genes.", example: "Eye color is inherited from your parents' genes.", remember: "Genes carry instructions; offspring resemble their parents.", cases: [["Inherited traits", "Passed down, like hair color."], ["Genes and chromosomes", "Genes sit on chromosomes inside cells."], ["Variation", "Offspring are similar but not identical to parents."]] },
    "human body": { title: "Human body systems", means: "The human body has systems of organs that work together to keep you alive and healthy.", example: "The heart and blood vessels form the circulatory system.", remember: "Each system has a job, and the systems work together.", cases: [["Circulatory", "The heart pumps blood through the body."], ["Respiratory", "The lungs take in oxygen."], ["Skeletal", "Bones support and protect the body."]] },
    "revolution": { title: "The American Revolution", means: "The American Revolution was the war in which the thirteen colonies won independence from Britain and formed a new nation.", example: "The Declaration of Independence was adopted in 1776.", remember: "Colonists wanted a voice in government \u2014 'no taxation without representation.'", cases: [["Causes", "Taxes and lack of representation angered colonists."], ["Declaration", "In 1776 the colonies declared independence."], ["Result", "The United States became an independent country."]] },
    "civil war": { title: "The Civil War", means: "The U.S. Civil War (1861\u20131865) was fought between the Northern and Southern states, largely over slavery and the future of the nation.", example: "President Lincoln issued the Emancipation Proclamation during the war.", remember: "The Union won, the nation stayed together, and slavery ended.", cases: [["Cause", "Disagreement over slavery divided the country."], ["Leaders", "Lincoln led the Union during the war."], ["Result", "The Union was preserved and slavery was abolished."]] },
    "world war": { title: "The World Wars", means: "The two World Wars were global conflicts in the 20th century that involved many nations and changed the world.", example: "The U.S. entered World War II after the attack on Pearl Harbor in 1941.", remember: "These wars reshaped nations, industry, and daily life.", cases: [["Alliances", "Countries joined sides such as the Allies and Axis."], ["Home front", "Civilians supported the war by working in factories."], ["Results", "New global organizations formed to keep peace."]] },
    "supply and demand": { title: "Supply and demand", means: "In a market, supply is how much of a good is available and demand is how much people want it. Together they influence price.", example: "When many buyers want a scarce item, its price tends to rise.", remember: "Prices act as signals for buyers and sellers.", cases: [["High demand", "Scarce, wanted goods cost more."], ["High supply", "Plentiful goods often cost less."], ["Balance", "Price settles where supply meets demand."]] },
    "civilization": { title: "Early civilizations", means: "A civilization is a complex society with cities, government, writing, and shared culture. Many early ones grew near rivers.", example: "Ancient Egypt developed along the Nile River.", remember: "Farming let people settle, build cities, and record history.", cases: [["Rivers", "Water supported farming and travel."], ["Writing", "Records helped organize society."], ["Government", "Leaders and laws organized large groups."]] },
    "map": { title: "Reading maps", means: "A map is a drawing that shows a place from above. Symbols, a key, a compass rose, and a scale help you read it.", example: "A compass rose shows north, south, east, and west.", remember: "Use the key to understand symbols and the scale to judge distance.", cases: [["Key/legend", "Explains what the symbols mean."], ["Compass rose", "Shows direction."], ["Scale", "Relates map distance to real distance."]] },
    "religion": { title: "World religions", means: "World religions are systems of shared beliefs, values, and traditions followed by many people around the world.", example: "Sacred texts and celebrations are part of many religions.", remember: "Learning about religions builds understanding of different cultures.", cases: [["Beliefs", "Shared ideas about meaning and values."], ["Texts", "Important books guide followers."], ["Traditions", "Celebrations and customs mark the year."]] },
    "water cycle": { title: "The water cycle", means: "The water cycle is the continuous movement of water between the oceans, the sky, and the land, powered by the sun.", example: "The sun evaporates ocean water, which condenses into clouds and falls as rain.", remember: "Evaporation \u2192 condensation \u2192 precipitation \u2192 collection, then it repeats.", cases: [["Evaporation", "The sun turns liquid water into invisible water vapor."], ["Condensation", "Vapor cools high in the air and forms clouds."], ["Precipitation", "Water falls back to Earth as rain, snow, or hail."]] },
    "rock": { title: "Rocks and minerals", means: "Rocks are natural solids made of minerals. Geologists sort rocks into three groups based on how they form.", example: "Granite is igneous, sandstone is sedimentary, and marble is metamorphic.", remember: "Igneous cools from melted rock; sedimentary forms in layers; metamorphic is changed by heat and pressure.", cases: [["Igneous", "Forms when melted rock cools and hardens."], ["Sedimentary", "Forms as layers of sediment press together."], ["Metamorphic", "Forms when heat and pressure change existing rock."]] },
    "life cycle": { title: "Life cycles", means: "A life cycle shows the stages a living thing passes through, from its beginning to adulthood and reproduction.", example: "A butterfly goes egg \u2192 larva (caterpillar) \u2192 pupa \u2192 adult.", remember: "Living things are born or hatch, grow, and then produce young of their own.", cases: [["Metamorphosis", "A butterfly or frog changes body form as it grows."], ["Direct growth", "A puppy simply grows larger into a dog."], ["Plants too", "A seed grows into a plant that makes new seeds."]] },
    "day and night": { title: "Day and night", means: "Day and night happen because Earth spins, or rotates, on its axis about once every 24 hours.", example: "The side of Earth facing the sun has day; the side facing away has night.", remember: "The sun does not move across the sky \u2014 Earth's rotation does.", cases: [["Rotation", "Earth spins once about every 24 hours."], ["Facing the sun", "The lit side has daytime."], ["Facing away", "The dark side has nighttime."]] },
    "season": { title: "Seasons", means: "Seasons happen because Earth's axis is tilted as the planet orbits the sun over a year.", example: "When your part of Earth tilts toward the sun, it is summer.", remember: "The tilt of Earth's axis, not its distance from the sun, causes the seasons.", cases: [["Tilt toward sun", "More direct sunlight brings summer."], ["Tilt away", "Less direct sunlight brings winter."], ["One year", "Earth orbits the sun once each year."]] },
    "magnet": { title: "Magnets", means: "A magnet is an object that can pull certain metals toward it and can push or pull other magnets without touching them.", example: "Two north poles pushed together repel each other.", remember: "Opposite poles attract; like poles repel.", cases: [["Attract", "Opposite poles (N and S) pull together."], ["Repel", "Like poles (N and N) push apart."], ["Magnetic metals", "Magnets attract iron, nickel, and cobalt."]] },
    "electric": { title: "Electricity and circuits", means: "Electricity is a form of energy from moving electric charges. It flows through a complete loop called a circuit.", example: "A battery, wires, and a bulb form a circuit that lights up.", remember: "Current flows only when the circuit is complete, or closed.", cases: [["Closed circuit", "A complete loop lets current flow."], ["Open circuit", "A break in the loop stops the current."], ["Conductors", "Metals let electricity flow; insulators do not."]] },
    "light": { title: "Light", means: "Light is a form of energy that travels in straight lines and lets us see objects.", example: "We see a book when light bounces off it and into our eyes.", remember: "Light can be reflected, absorbed, or pass through materials.", cases: [["Reflection", "Light bounces off surfaces like mirrors."], ["Absorption", "Dark objects absorb more light and warm up."], ["Transparency", "Light passes through clear materials like glass."]] },
    "heat": { title: "Heat and thermal energy", means: "Thermal energy is the energy of moving particles. Heat is thermal energy moving from a warmer object to a cooler one.", example: "A metal spoon warms up when placed in hot soup.", remember: "Heat always flows from hot to cold until temperatures are equal.", cases: [["Conduction", "Heat moves through direct contact."], ["Direction", "Heat flows from warmer to cooler objects."], ["Thermometer", "Measures how hot or cold something is."]] },
    "fossil": { title: "Fossils", means: "A fossil is the preserved remains or trace of a living thing from long ago, often found in rock.", example: "A dinosaur bone that has turned to stone is a fossil.", remember: "Fossils give evidence about organisms and environments of the past.", cases: [["Body fossils", "Bones, shells, or teeth preserved in rock."], ["Trace fossils", "Footprints or burrows left behind."], ["Rock layers", "Deeper layers usually hold older fossils."]] },
    "planet": { title: "The solar system", means: "The solar system is the sun and everything that orbits it, including eight planets, their moons, and smaller bodies.", example: "Earth is the third planet from the sun.", remember: "Planets orbit the sun; moons orbit planets.", cases: [["The sun", "A star at the center that gives light and heat."], ["Eight planets", "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune."], ["Moons", "Natural satellites that orbit planets."]] },
    "reaction": { title: "Chemical reactions", means: "In a chemical reaction, substances combine or change to form new substances with different properties.", example: "When iron combines with oxygen over time, it forms rust.", remember: "New substances form, and matter is conserved \u2014 not created or destroyed.", cases: [["Signs of a reaction", "Color change, gas bubbles, heat, or light."], ["Reactants and products", "Starting substances become new products."], ["Conservation of mass", "The total mass stays the same."]] },
    "periodic table": { title: "The periodic table", means: "The periodic table organizes all known chemical elements by their number of protons and shared properties.", example: "Hydrogen (H) is element 1; oxygen (O) is element 8.", remember: "Elements in the same column tend to have similar properties.", cases: [["Symbols", "Each element has a one- or two-letter symbol."], ["Atomic number", "Equals the number of protons in an atom."], ["Groups", "Columns group elements that behave alike."]] },
    "plate tectonic": { title: "Plate tectonics", means: "Earth's outer shell is broken into large plates that move slowly, reshaping the surface over long periods of time.", example: "Two plates pushing together can slowly build mountains.", remember: "Plate movement causes earthquakes, volcanoes, and mountains.", cases: [["Collide", "Plates crashing together build mountains."], ["Spread apart", "Plates separating form new crust."], ["Slide past", "Plates grinding past each other cause earthquakes."]] },
    "evolution": { title: "Evolution", means: "Evolution is the gradual change in the inherited traits of a species over many generations.", example: "Over time, birds with beaks suited to their food became more common.", remember: "Traits that help survival are passed on more often \u2014 this is natural selection.", cases: [["Variation", "Individuals in a species differ in their traits."], ["Selection", "Traits that aid survival are passed on more often."], ["Over time", "Species change across many generations."]] },
    "wave": { title: "Waves", means: "A wave is a disturbance that carries energy from one place to another, such as sound waves or light waves.", example: "Dropping a stone in water makes ripples that spread outward.", remember: "Waves carry energy, not matter, from place to place.", cases: [["Amplitude", "The height of a wave; taller waves carry more energy."], ["Wavelength", "The distance between one wave peak and the next."], ["Types", "Sound, light, and water waves all carry energy."]] },
  };

  function getConcept(skill) {
    if (skill.type && BY_TYPE[skill.type]) return BY_TYPE[skill.type];
    const lower = (skill.name || "").toLowerCase();
    for (const key in BY_KEYWORD) {
      if (lower.indexOf(key) >= 0) return BY_KEYWORD[key];
    }
    // Generic fallback derived from the skill name.
    return {
      title: skill.name,
      means: "This skill builds understanding of " + skill.name.toLowerCase() + ". Read each question carefully and use what you know to choose the best-supported answer.",
      example: "Look for key words in the question that point to the correct idea.",
      remember: "Slow down, check every choice, and rule out answers that do not fit.",
      cases: [["Read fully", "Read the whole question before choosing."],
        ["Eliminate", "Cross out choices that are clearly wrong first."],
        ["Best supported", "Pick the answer with the strongest reason behind it."]],
    };
  }

  // Map skill types to the reference SVG visuals (concept-visuals.js).
  const TYPE_VISUAL = {
    place: "__PLACE__", round: "Rounding",
    add: "Add & subtract", add3: "Add & subtract", sub: "Add & subtract",
    mul: "Area models", div: "Long division",
    "frac-add": "Adding fractions", "frac-sub": "Subtracting fractions",
    "int-add": "Integers", "int-mul": "Integers", abs: "Absolute value",
    eval: "Expressions", linear: "Variables", linear2: "Variables",
    slope: "Coordinate plane", area: "Area", "area-tri": "Area",
    perimeter: "Perimeter", volume: "Volume",
  };

  function getVisual(skill) {
    const key = TYPE_VISUAL[skill && skill.type];
    if (!key) return "";
    if (key === "__PLACE__") return global.PLACE_VALUE_VISUAL || "";
    const map = global.CONCEPT_VISUALS;
    return (map && map[key]) || "";
  }

  global.CONCEPTS = { getConcept: getConcept, getVisual: getVisual, BY_TYPE: BY_TYPE, BY_KEYWORD: BY_KEYWORD };
})(window);
