/* FreeSchoolEducation - Middle-grades reading comprehension (grades 6-8)
 * Detailed, topic-specific passages with more questions than elementary.
 * Question counts: grade 6 = 7, grade 7 = 8, grade 8 = 10 (maximum content).
 * Shape consumed by reading.js: ReadingMiddle[gradeId] = [{ name, stories:[{title, paragraphs, questions}] }]
 * questions: [prompt, correct, distractor, distractor, distractor]
 */
(function (global) {
  "use strict";

  const GRADE6 = [
    { name: "Science & Discovery", stories: [
      { title: "Photosynthesis: How Plants Make Food", paragraphs: [
        "Plants may look still and quiet, but inside their leaves a remarkable process is always at work. It is called photosynthesis, and it is how green plants make their own food. Without it, most life on Earth could not exist.",
        "Photosynthesis takes place mainly in the leaves, inside tiny structures called chloroplasts. Chloroplasts contain a green pigment named chlorophyll, which gives leaves their color and captures energy from sunlight.",
        "During photosynthesis, a plant takes in carbon dioxide from the air through small openings in its leaves and absorbs water through its roots. Using the energy from sunlight, it combines these into a sugar called glucose, which the plant uses for energy and growth. The process also releases oxygen into the air.",
        "Because plants make both food and oxygen, they form the base of almost every food chain. Animals cannot make their own food, so they depend, directly or indirectly, on the sugars that plants create."],
        questions: [
          ["What is photosynthesis?", "How green plants make their own food", "How plants sleep at night", "How animals breathe underwater", "How rain clouds form"],
          ["Inside which structures does photosynthesis mainly happen?", "Chloroplasts", "Roots", "Seeds", "Stems only"],
          ["Which pigment captures energy from sunlight?", "Chlorophyll", "Glucose", "Oxygen", "Carbon"],
          ["Which gas does a plant take in during photosynthesis?", "Carbon dioxide", "Oxygen", "Helium", "Nitrogen"],
          ["What sugar does photosynthesis produce?", "Glucose", "Table salt", "Sand", "Protein"],
          ["What gas is released as a result of photosynthesis?", "Oxygen", "Carbon dioxide", "Hydrogen", "Smoke"],
          ["Why are plants the base of most food chains?", "They make food and oxygen that other living things depend on", "They move faster than animals", "They eat other animals", "They never need water"]] },
      { title: "The Water Cycle", paragraphs: [
        "The water on Earth is always moving in a repeating pattern called the water cycle. Powered by the sun, it moves water between the oceans, the sky, and the land.",
        "The sun heats water in oceans, lakes, and rivers, turning it into an invisible gas called water vapor. This step is evaporation. Plants add moisture to the air too, through a process called transpiration.",
        "High in the cooler air, the vapor condenses into tiny droplets that gather to form clouds. When the droplets grow heavy enough, they fall back to Earth as rain, snow, or hail. This falling water is called precipitation.",
        "Water that lands on the ground flows into streams and rivers, soaks into the soil, or collects underground. Eventually it returns to the oceans, and the cycle begins again, providing the fresh water that living things need."],
        questions: [
          ["What powers the water cycle?", "The sun", "The wind alone", "Cars and machines", "The moon's gravity only"],
          ["What is evaporation?", "Water turning into vapor", "Rain falling to the ground", "Clouds turning to ice", "Rivers freezing solid"],
          ["What is the process by which plants add moisture to the air?", "Transpiration", "Erosion", "Digestion", "Rotation"],
          ["How do clouds form?", "Water vapor condenses into droplets", "Rain freezes on the ground", "Dust blows into the sky", "The sun sets"],
          ["What is precipitation?", "Rain, snow, or hail falling to Earth", "Water heating up", "Vapor rising", "Rivers drying out"],
          ["Where does most fallen water eventually return?", "To the oceans", "To outer space", "Into the sun", "Nowhere \u2014 it disappears"],
          ["What is the main idea of the passage?", "Water moves through a repeating cycle that supplies fresh water", "Rain only falls in winter", "Oceans never change", "Clouds are made of dust"]] },
    ]},
    { name: "Inventions & Technology", stories: [
      { title: "The Printing Press and the Spread of Ideas", paragraphs: [
        "Before the 1400s, books in Europe were copied slowly by hand, usually by scribes working for months on a single volume. Because each copy took so long, books were rare and expensive, and few people could read.",
        "Around 1440, a German craftsman named Johannes Gutenberg developed a printing press that used movable metal type. Letters could be arranged into words, inked, and pressed onto paper, then rearranged to print a different page. Many copies could now be made quickly.",
        "As printing spread, the number of books grew rapidly and prices dropped. More people learned to read, and new ideas about science, religion, and government traveled farther and faster than ever before.",
        "Historians often call the printing press one of the most important inventions in history. By making knowledge widely available, it helped spark movements such as the Renaissance and the Reformation."],
        questions: [
          ["How were most European books made before the printing press?", "Copied slowly by hand", "Printed by machines", "Typed on computers", "Not made at all"],
          ["Who developed the movable-type printing press around 1440?", "Johannes Gutenberg", "Thomas Edison", "Isaac Newton", "Galileo"],
          ["Why were books rare before printing?", "Copying by hand was slow and costly", "No one wanted them", "Paper did not exist", "They were forbidden by law"],
          ["What did the press use to print pages?", "Movable metal type", "Handwriting", "Stone carvings", "Wax seals"],
          ["What happened to book prices as printing spread?", "They dropped", "They rose sharply", "They stayed fixed forever", "Books became free instantly"],
          ["What was one effect of cheaper books?", "More people learned to read", "Fewer people read", "Ideas stopped spreading", "Schools closed"],
          ["Which movements did the printing press help spark?", "The Renaissance and the Reformation", "The Ice Age", "The Space Race", "The Stone Age"],
          ["What is the author's main point?", "Making knowledge widely available can change society", "Handwriting is faster than printing", "Books should stay rare", "Reading is unimportant"]] },
      { title: "The Telegraph: Messages at the Speed of Electricity", paragraphs: [
        "For most of history, a message could travel only as fast as a person on horseback or a ship at sea. Sending news across a country could take weeks.",
        "In the 1830s and 1840s, inventors including Samuel Morse developed the electric telegraph. It sent pulses of electricity along wires. Using a code of short and long signals \u2014 dots and dashes known as Morse code \u2014 operators could spell out messages almost instantly.",
        "Telegraph lines soon stretched across continents, and later cables were laid across the ocean floor. For the first time, people far apart could exchange news within minutes instead of weeks.",
        "The telegraph changed business, journalism, and daily life. It also laid the groundwork for later inventions like the telephone and the internet, which continued the work of sending information over long distances."],
        questions: [
          ["Before the telegraph, how fast could a message travel?", "Only as fast as a horse or ship", "Instantly", "At the speed of light", "Faster than sound"],
          ["Who was one inventor of the electric telegraph?", "Samuel Morse", "Marie Curie", "Henry Ford", "Charles Darwin"],
          ["What did the telegraph send along wires?", "Pulses of electricity", "Sound waves", "Beams of light", "Paper notes"],
          ["What was the code of dots and dashes called?", "Morse code", "Binary code", "Zip code", "Area code"],
          ["Where were some telegraph cables placed?", "Across the ocean floor", "In outer space", "Underground in mines only", "Inside volcanoes"],
          ["How quickly could distant people exchange news with the telegraph?", "Within minutes", "Within weeks", "Within months", "Never"],
          ["Which later inventions built on the telegraph's work?", "The telephone and the internet", "The wheel and the plow", "The compass and the map", "The candle and the lamp"]] },
    ]},
    { name: "History & Society", stories: [
      { title: "Ancient Egypt and the Nile", paragraphs: [
        "Ancient Egypt was one of the world's earliest and longest-lasting civilizations. It grew along the banks of the Nile River in northeastern Africa more than 5,000 years ago.",
        "Each year the Nile flooded, leaving behind rich, dark soil perfect for farming. Reliable harvests of wheat and barley allowed the Egyptians to build cities, support a government, and free some people to work as artists, priests, and builders.",
        "The Egyptians are famous for their pyramids, enormous stone tombs built for their kings, called pharaohs. They also developed a writing system of picture symbols known as hieroglyphs and made advances in mathematics and medicine.",
        "Egyptian civilization lasted for thousands of years. Its monuments, writings, and art still teach us about how one of history's great societies lived and thought."],
        questions: [
          ["Along which river did ancient Egypt grow?", "The Nile", "The Amazon", "The Mississippi", "The Thames"],
          ["Why was the Nile's yearly flood important?", "It left rich soil for farming", "It destroyed all crops", "It cooled the desert", "It brought gold"],
          ["What crops did the Egyptians grow?", "Wheat and barley", "Corn and potatoes", "Rice and tea", "Coffee and cocoa"],
          ["What were the pyramids built to be?", "Tombs for kings", "Schools", "Markets", "Bridges"],
          ["What were Egyptian kings called?", "Pharaohs", "Presidents", "Emperors", "Knights"],
          ["What was the Egyptian writing of picture symbols called?", "Hieroglyphs", "The alphabet", "Morse code", "Numerals"],
          ["What is the main idea of the passage?", "The Nile helped Egypt become a great, lasting civilization", "Egypt had no farming", "Pyramids were homes", "Egypt lasted only a few years"]] },
      { title: "The Roman Empire", paragraphs: [
        "The Roman Empire was one of the most powerful states in the ancient world. Centered on the city of Rome in Italy, it eventually ruled lands around the entire Mediterranean Sea.",
        "Rome was known for its strong army and its skill in engineering. Roman builders constructed roads, bridges, and aqueducts \u2014 channels that carried fresh water into cities. Many of these structures still stand today.",
        "The Romans also created a system of written laws that treated citizens according to shared rules. Ideas from Roman law and government influenced many later nations, including the United States.",
        "Over centuries the empire grew too large to defend, and it faced invasions and internal problems. The western part of the empire finally fell in 476 CE, but Rome's language, laws, and engineering shaped the world that followed."],
        questions: [
          ["What city was the center of the Roman Empire?", "Rome", "Athens", "Cairo", "London"],
          ["Around which sea did Rome rule many lands?", "The Mediterranean Sea", "The Pacific Ocean", "The Arctic Ocean", "The Red Sea only"],
          ["What did Roman aqueducts carry?", "Fresh water into cities", "Soldiers into battle", "Gold to the emperor", "Ships to the sea"],
          ["What was Rome known for building?", "Roads, bridges, and aqueducts", "Skyscrapers", "Railroads", "Airports"],
          ["What did the Romans create that influenced later nations?", "A system of written laws", "The internet", "Gunpowder", "The printing press"],
          ["When did the western Roman Empire fall?", "476 CE", "1776 CE", "1000 BCE", "1492 CE"],
          ["Which country was influenced by Roman law and government?", "The United States", "No country", "Only Egypt", "Only China"]] },
    ]},
  ];

  const GRADE7 = [
    { name: "Life Science", stories: [
      { title: "Cells: The Building Blocks of Life", paragraphs: [
        "Every living thing, from the tallest tree to the smallest bacterium, is made of cells. A cell is the smallest unit that can carry out the basic processes of life, such as taking in nutrients and using energy.",
        "Some organisms, like many bacteria, are made of just one cell. Others, like humans, are made of trillions of cells that work together. Groups of similar cells form tissues, tissues form organs, and organs form the systems that keep a body running.",
        "Inside each cell are tiny structures called organelles, each with a special job. The nucleus stores the cell's instructions in a molecule called DNA. Mitochondria release energy from food, and the cell membrane controls what enters and leaves.",
        "Plant cells have some features animal cells lack, such as a stiff cell wall and green chloroplasts for photosynthesis. Studying cells helps scientists understand health, disease, and how living things grow.",
        "When cells become damaged or worn out, the body replaces them by having existing cells divide. This ability to grow and repair is one of the key features of living things."],
        questions: [
          ["What is a cell?", "The smallest unit that carries out life processes", "A type of mineral", "A large organ", "A nonliving crystal"],
          ["How many cells make up a human?", "Trillions", "Exactly one", "About ten", "None"],
          ["What do groups of similar cells form?", "Tissues", "Rocks", "Planets", "Weather"],
          ["What does the nucleus store?", "The cell's instructions in DNA", "Extra food", "Waste only", "Water only"],
          ["Which organelle releases energy from food?", "Mitochondria", "The cell wall", "The nucleus", "The membrane"],
          ["What controls what enters and leaves a cell?", "The cell membrane", "The nucleus", "The mitochondria", "The DNA"],
          ["Which feature do plant cells have that animal cells lack?", "A stiff cell wall", "A nucleus", "A membrane", "Cytoplasm"],
          ["How does the body replace damaged cells?", "Existing cells divide", "Cells shrink away", "New organs appear", "Cells freeze"]] },
      { title: "Ecosystems and the Flow of Energy", paragraphs: [
        "An ecosystem is a community of living things interacting with each other and with the non-living parts of their environment, such as sunlight, water, air, and soil. A forest, a pond, and a desert are all ecosystems.",
        "Energy enters most ecosystems as sunlight. Producers, mainly green plants, capture that energy and use it to make food. Consumers, such as animals, get energy by eating producers or other consumers.",
        "Scientists trace energy through food chains and the larger, connected webs called food webs. At each step, some energy is used up, so food chains usually have only a few links. Decomposers, like fungi and bacteria, break down dead matter and return nutrients to the soil.",
        "Ecosystems stay balanced when producers, consumers, and decomposers all play their roles. If one part changes \u2014 for example, if a predator disappears \u2014 the effects can spread through the whole community.",
        "Understanding ecosystems helps people protect the environment and use natural resources wisely."],
        questions: [
          ["What is an ecosystem?", "A community of living things and their environment", "Only a group of animals", "A single rock", "A type of weather"],
          ["How does energy usually enter an ecosystem?", "As sunlight", "As electricity", "From the soil only", "From the wind only"],
          ["What do producers do?", "Capture energy to make food", "Only eat other animals", "Break down dead matter", "Store water"],
          ["What are animals that eat producers or other animals called?", "Consumers", "Producers", "Decomposers", "Minerals"],
          ["Why do food chains usually have only a few links?", "Some energy is used up at each step", "Animals refuse to eat", "Plants block them", "The sun stops shining"],
          ["What do decomposers do?", "Break down dead matter and recycle nutrients", "Make sunlight", "Hunt live prey", "Produce oxygen only"],
          ["What can happen if a predator disappears?", "Effects can spread through the whole community", "Nothing changes at all", "The sun gets brighter", "Plants become animals"],
          ["Why is understanding ecosystems useful?", "It helps people protect the environment", "It stops the water cycle", "It ends all food chains", "It removes decomposers"]] },
      { title: "Genetics and Heredity", paragraphs: [
        "Have you ever been told you have your grandmother's eyes or your father's smile? The passing of traits from parents to offspring is called heredity, and the science that studies it is called genetics.",
        "Traits are carried by genes, which are sections of a long molecule called DNA. DNA is found on structures called chromosomes inside the nucleus of each cell. Offspring receive a mix of genes from both parents, which is why children resemble their parents but are not identical to them.",
        "In the 1860s, a monk named Gregor Mendel studied pea plants and discovered patterns in how traits are inherited. His careful experiments earned him the title 'father of genetics.'",
        "Some traits, like eye color, are largely inherited. Others depend on both genes and the environment. Today, scientists use genetics to fight disease, improve crops, and understand living things more deeply."],
        questions: [
          ["What is heredity?", "The passing of traits from parents to offspring", "The study of rocks", "A type of weather", "A kind of food"],
          ["What are traits carried by?", "Genes", "Muscles", "Bones only", "Water"],
          ["Where is DNA found in a cell?", "On chromosomes in the nucleus", "In the cell wall", "Outside the cell", "In the mitochondria only"],
          ["Why do children resemble their parents but differ from them?", "They receive a mix of genes from both parents", "They copy one parent exactly", "Genes never pass down", "They choose their traits"],
          ["Who studied pea plants and found patterns of inheritance?", "Gregor Mendel", "Isaac Newton", "Charles Darwin", "Marie Curie"],
          ["What title did Mendel earn?", "Father of genetics", "Father of physics", "Father of chemistry", "Father of astronomy"],
          ["Besides genes, what can affect some traits?", "The environment", "Nothing at all", "Only luck", "The weather forecast"],
          ["How do scientists use genetics today?", "To fight disease and improve crops", "To stop the water cycle", "To make rocks", "To slow the sun"]] },
    ]},
    { name: "Technology & Industry", stories: [
      { title: "The Steam Engine and the Industrial Revolution", paragraphs: [
        "In the 1700s, most goods were made by hand in homes and small workshops, and most power came from muscle, wind, or flowing water. Then a new machine began to change everything: the steam engine.",
        "A steam engine burns fuel, usually coal, to boil water into steam. The expanding steam pushes parts that turn wheels and drive machinery. Inventors such as James Watt greatly improved the engine, making it powerful and reliable.",
        "With steam power, factories could run many machines at once and did not have to be built beside rivers. This helped launch the Industrial Revolution, a period when manufacturing shifted from homes to factories and cities grew rapidly.",
        "Steam engines also powered locomotives and steamships, moving goods and people faster than ever. The changes brought new products and jobs, but also crowded cities and difficult working conditions that societies had to address."],
        questions: [
          ["Before the steam engine, where did most power come from?", "Muscle, wind, or flowing water", "Electricity", "Nuclear plants", "Solar panels"],
          ["What does a steam engine burn to make steam?", "Fuel such as coal", "Ice", "Sand", "Air only"],
          ["What does the expanding steam do?", "Pushes parts that turn machinery", "Cools the engine", "Makes light", "Stops motion"],
          ["Who greatly improved the steam engine?", "James Watt", "Thomas Jefferson", "Albert Einstein", "Christopher Columbus"],
          ["Why didn't steam-powered factories need to be by rivers?", "Steam provided the power instead of water wheels", "They used wind only", "They needed no power", "Rivers were banned"],
          ["What period did steam power help launch?", "The Industrial Revolution", "The Ice Age", "The Renaissance", "The Space Age"],
          ["What else did steam engines power?", "Locomotives and steamships", "Airplanes and rockets", "Computers", "Satellites"],
          ["What problems came with rapid industrial growth?", "Crowded cities and hard working conditions", "Too few jobs to fill", "No new products", "Slower travel"]] },
      { title: "The Telephone", paragraphs: [
        "The telegraph let people send coded messages over wires, but many inventors dreamed of sending the human voice itself. In 1876, Alexander Graham Bell was granted a patent for the telephone.",
        "A telephone changes the sound of a voice into an electrical signal. That signal travels along a wire to another telephone, which turns it back into sound. For the first time, people could speak with one another across long distances in real time.",
        "Telephone networks spread quickly. Wires connected homes, businesses, and eventually whole countries. Operators once connected calls by hand before automatic switching took over.",
        "The telephone reshaped how people communicate, work, and stay in touch with family. It also set the stage for the mobile phones and smartphones that billions of people rely on today."],
        questions: [
          ["What did many inventors want to send that the telegraph could not?", "The human voice", "Written letters", "Photographs", "Packages"],
          ["Who was granted a patent for the telephone in 1876?", "Alexander Graham Bell", "Samuel Morse", "Thomas Edison", "Henry Ford"],
          ["What does a telephone change a voice into?", "An electrical signal", "A beam of light", "A paper message", "A radio wave only"],
          ["What does the receiving telephone do with the signal?", "Turns it back into sound", "Prints it on paper", "Stores it as a photo", "Deletes it"],
          ["What was new about the telephone compared with the telegraph?", "People could speak in real time across distances", "It used no wires", "It sent only codes", "It worked underwater only"],
          ["Who once connected telephone calls by hand?", "Operators", "Robots", "Farmers", "Soldiers"],
          ["What later devices grew out of the telephone?", "Mobile phones and smartphones", "Steam engines", "Printing presses", "Telescopes"],
          ["What is the main idea of the passage?", "The telephone let people speak across distances and led to modern phones", "The telephone replaced farming", "Telephones send only codes", "Phones were never popular"]] },
    ]},
    { name: "World History", stories: [
      { title: "Ancient Greece and the Birth of Democracy", paragraphs: [
        "Ancient Greece was not a single country but a collection of independent city-states, each with its own government. The most famous of these was Athens.",
        "Around 2,500 years ago, Athens developed an early form of democracy, a word that means 'rule by the people.' Male citizens could gather to debate and vote directly on laws and decisions. Although many people, including women and enslaved people, were excluded, the idea that ordinary people could share in government was revolutionary.",
        "The Greeks also made lasting contributions to philosophy, science, art, and sports. Thinkers such as Socrates, Plato, and Aristotle asked deep questions about knowledge and how people should live. The Olympic Games began in Greece as well.",
        "Greek ideas about government, reason, and beauty spread widely and still influence the modern world, including how many nations run their governments today."],
        questions: [
          ["How was ancient Greece organized?", "As independent city-states", "As one large empire", "As a single kingdom", "As modern countries"],
          ["Which city-state was most famous?", "Athens", "Rome", "Cairo", "Paris"],
          ["What does the word 'democracy' mean?", "Rule by the people", "Rule by one king", "Rule by priests", "Rule by soldiers"],
          ["In Athens, who could vote directly on laws?", "Male citizens", "Everyone in the city", "Only the king", "Foreign traders"],
          ["Who were some famous Greek thinkers?", "Socrates, Plato, and Aristotle", "Newton and Einstein", "Edison and Bell", "Caesar and Nero"],
          ["What famous games began in Greece?", "The Olympic Games", "The World Cup", "The Super Bowl", "The Tour de France"],
          ["Why was Athenian democracy revolutionary despite excluding many people?", "It let ordinary people share in government", "It gave power to one ruler", "It banned all voting", "It had no laws"],
          ["How do Greek ideas affect the modern world?", "They influence how many nations govern", "They stopped all science", "They were forgotten", "They apply only to sports"]] },
      { title: "Life in the Middle Ages", paragraphs: [
        "The Middle Ages, or medieval period, lasted in Europe from roughly 500 to 1500 CE, after the fall of the western Roman Empire. It was a time of kings, castles, knights, and a system of land and loyalty called feudalism.",
        "Under feudalism, kings granted land to nobles in exchange for military service. Nobles, in turn, relied on peasants who farmed the land. Most people were peasants who worked hard and rarely traveled far from home.",
        "The Christian Church was powerful in medieval Europe. It ran schools, cared for the sick, and shaped daily life. Monks in monasteries copied books by hand, helping to preserve knowledge.",
        "Later in the period, trade grew, towns expanded, and universities were founded. These changes helped set the stage for the Renaissance, a great revival of art and learning."],
        questions: [
          ["About when did the Middle Ages take place in Europe?", "Roughly 500 to 1500 CE", "About 2000 BCE", "The 1800s", "The 1900s"],
          ["The Middle Ages began after the fall of what?", "The western Roman Empire", "Ancient Egypt", "The United States", "The Greek city-states"],
          ["What was the system of land and loyalty called?", "Feudalism", "Democracy", "Capitalism", "Socialism"],
          ["Under feudalism, what did kings grant nobles?", "Land in exchange for military service", "Gold coins only", "Ships", "Books"],
          ["Who farmed the land?", "Peasants", "Kings", "Knights only", "Merchants"],
          ["What powerful institution shaped daily life?", "The Christian Church", "The internet", "A national army", "A stock market"],
          ["How did monks help preserve knowledge?", "They copied books by hand", "They burned libraries", "They banned reading", "They built factories"],
          ["What great revival did the later Middle Ages help set the stage for?", "The Renaissance", "The Ice Age", "The Industrial Revolution only", "The Stone Age"]] },
      { title: "The Renaissance", paragraphs: [
        "Beginning in Italy around the 1300s and spreading across Europe, the Renaissance was a period of renewed interest in art, learning, and the ideas of ancient Greece and Rome. The word 'renaissance' means 'rebirth.'",
        "Wealthy families and cities paid artists and thinkers to create new works. Painters such as Leonardo da Vinci and Michelangelo produced masterpieces, while writers explored human experience in fresh ways.",
        "Renaissance thinkers valued observation and human potential. This spirit encouraged scientists to study the natural world carefully, helping to lay the foundations of modern science.",
        "The printing press, invented during this era, spread Renaissance ideas quickly. The period reshaped European art, science, and thought, and its influence still surrounds us today."],
        questions: [
          ["Where did the Renaissance begin?", "In Italy", "In Egypt", "In China", "In the Americas"],
          ["What does the word 'renaissance' mean?", "Rebirth", "Darkness", "War", "Silence"],
          ["Which ancient cultures inspired the Renaissance?", "Greece and Rome", "Egypt and Persia", "China and India", "The Aztecs and Maya"],
          ["Who were two famous Renaissance painters?", "Leonardo da Vinci and Michelangelo", "Newton and Galileo", "Bell and Edison", "Caesar and Cleopatra"],
          ["What did Renaissance thinkers value?", "Observation and human potential", "Ignoring the world", "Only warfare", "Avoiding art"],
          ["What invention helped spread Renaissance ideas?", "The printing press", "The telephone", "The steam engine", "The computer"],
          ["What did the Renaissance help lay the foundations of?", "Modern science", "The Middle Ages", "Ancient Egypt", "The Ice Age"],
          ["What is the main idea of the passage?", "The Renaissance revived art and learning and shaped the modern world", "The Renaissance stopped all art", "It happened only in Egypt", "It had no lasting effect"]] },
    ]},
  ];

  const GRADE8 = [
    { name: "Physical & Life Science", stories: [
      { title: "Atoms and the Periodic Table", paragraphs: [
        "Everything around you \u2014 air, water, your own body \u2014 is made of tiny particles called atoms. Atoms are so small that millions could fit across the width of a human hair.",
        "An atom has a dense center called the nucleus, which contains positively charged protons and neutral neutrons. Negatively charged electrons move in the space around the nucleus. The number of protons determines what element an atom is.",
        "A substance made of only one kind of atom is called an element. Hydrogen, oxygen, gold, and iron are all elements. Scientists organize the known elements in a chart called the periodic table.",
        "The periodic table arranges elements by their number of protons and groups those with similar properties into columns. This organization lets scientists predict how elements will behave and how they might combine.",
        "When atoms of different elements join, they form compounds. Water, for example, is a compound made of hydrogen and oxygen atoms. Understanding atoms is the foundation of chemistry.",
        "By learning how atoms bond and react, scientists can design new materials, medicines, and technologies that shape everyday life."],
        questions: [
          ["What is everything around us made of?", "Atoms", "Only water", "Only metal", "Empty space"],
          ["What is the dense center of an atom called?", "The nucleus", "The electron", "The shell", "The compound"],
          ["Which particles are found in the nucleus?", "Protons and neutrons", "Only electrons", "Only protons", "No particles"],
          ["What charge do electrons carry?", "Negative", "Positive", "No charge", "Both charges"],
          ["What determines which element an atom is?", "The number of protons", "The color", "The temperature", "The size of the room"],
          ["What is a substance made of only one kind of atom?", "An element", "A mixture", "A solution", "A machine"],
          ["What chart organizes the known elements?", "The periodic table", "A food web", "A number line", "A map"],
          ["How does the periodic table group elements?", "By protons and similar properties", "By color only", "By price", "By age"],
          ["What forms when atoms of different elements join?", "Compounds", "Nothing", "Only gases", "Only metals"],
          ["Why is understanding atoms important?", "It is the foundation of chemistry and new technology", "It stops all reactions", "It has no real use", "It only applies to gold"]] },
      { title: "Newton's Laws of Motion", paragraphs: [
        "In the 1600s, the English scientist Isaac Newton described three laws that explain how objects move. These laws are still used today to design everything from cars to spacecraft.",
        "Newton's first law states that an object at rest stays at rest, and an object in motion stays in motion at a constant speed and direction, unless an unbalanced force acts on it. This tendency to resist change in motion is called inertia.",
        "The second law explains that the acceleration of an object depends on the force applied and the object's mass. A greater force produces greater acceleration, while a heavier object accelerates less for the same force. This is often written as force equals mass times acceleration.",
        "The third law states that for every action there is an equal and opposite reaction. When you push against a wall, the wall pushes back on you with equal force. Rockets rise because they push gas downward, and the gas pushes the rocket upward.",
        "Together, Newton's laws explain the motion of ordinary objects with remarkable accuracy. They form a cornerstone of physics and engineering.",
        "Even as newer theories describe the very fast and very small, Newton's laws remain essential tools for understanding the everyday world."],
        questions: [
          ["Who described three laws of motion in the 1600s?", "Isaac Newton", "Albert Einstein", "Galileo Galilei", "Thomas Edison"],
          ["What does the first law say about an object in motion?", "It keeps moving unless an unbalanced force acts on it", "It always slows down on its own", "It speeds up forever", "It cannot move at all"],
          ["What is the tendency to resist changes in motion called?", "Inertia", "Gravity", "Friction", "Energy"],
          ["According to the second law, what affects acceleration?", "The force applied and the object's mass", "Only the color", "Only the time of day", "The object's price"],
          ["For the same force, how does a heavier object accelerate?", "Less than a lighter object", "More than a lighter object", "Exactly the same", "It cannot accelerate"],
          ["What does the third law state?", "For every action there is an equal and opposite reaction", "Objects never react", "Forces always cancel to zero", "Only heavy things move"],
          ["Why does a rocket rise?", "It pushes gas down, and the gas pushes it up", "It has no mass", "Gravity pushes it up", "It floats on air"],
          ["What field uses Newton's laws to design machines?", "Engineering", "Painting", "Cooking", "Music"],
          ["What is one everyday example of the third law?", "Pushing a wall and feeling it push back", "A plant growing", "Rain falling", "Ice melting"],
          ["What is the main idea of the passage?", "Newton's three laws explain how objects move", "Newton studied plants", "Motion cannot be explained", "Only rockets obey the laws"]] },
      { title: "DNA and Cell Division", paragraphs: [
        "Inside almost every cell of a living thing is a set of instructions written in a molecule called DNA. DNA carries the genetic code that tells cells how to build and run an organism.",
        "DNA is shaped like a twisted ladder known as a double helix. The rungs of the ladder are pairs of chemical bases, and the order of these bases spells out the instructions, much like letters spell out words.",
        "For an organism to grow or repair itself, its cells must divide. Before a cell divides, it makes a complete copy of its DNA so that each new cell receives the full set of instructions. This process of copying and dividing is carefully controlled.",
        "In a type of division called mitosis, one cell divides into two identical cells. This is how bodies grow and replace worn-out cells. A different process, called meiosis, produces sex cells with half the usual DNA, which combine during reproduction.",
        "Mistakes in copying DNA can sometimes cause problems, but they can also create the variation that helps species adapt over time.",
        "Understanding DNA and cell division has transformed medicine, agriculture, and our knowledge of life itself."],
        questions: [
          ["What molecule carries the genetic code?", "DNA", "Water", "Oxygen", "Salt"],
          ["What shape is DNA?", "A twisted ladder, or double helix", "A flat square", "A solid ball", "A straight line"],
          ["What do the order of DNA's bases spell out?", "The instructions for the organism", "Random noise", "The weather", "A phone number"],
          ["Why must cells copy their DNA before dividing?", "So each new cell gets the full instructions", "To make less DNA", "To destroy the DNA", "To change species"],
          ["What is the division that makes two identical cells called?", "Mitosis", "Meiosis", "Evaporation", "Erosion"],
          ["What does mitosis allow bodies to do?", "Grow and replace worn-out cells", "Stop growing", "Lose all cells", "Turn into plants"],
          ["What does meiosis produce?", "Sex cells with half the usual DNA", "Extra bones", "New elements", "More water"],
          ["What can mistakes in copying DNA sometimes create?", "Variation that helps species adapt", "Nothing at all", "New planets", "More sunlight"],
          ["Where is DNA found?", "Inside almost every cell", "Only in the blood", "Outside the body", "In rocks"],
          ["How has understanding DNA affected the world?", "It has transformed medicine and agriculture", "It ended all science", "It has no uses", "It only affects plants"]] },
    ]},
    { name: "Technology & Medicine", stories: [
      { title: "The Internet: Connecting the World", paragraphs: [
        "The internet is a vast network that links billions of computers and devices so they can share information almost instantly. It began in the 1960s as a research project to help separate computer networks communicate.",
        "To let very different machines exchange data reliably, engineers agreed on shared rules called protocols. Because information is broken into small packets that can travel along many possible paths, the network is flexible and hard to shut down completely.",
        "In the 1990s, the World Wide Web made the internet easy to use by linking documents through clickable pages. Web browsers and search engines soon allowed ordinary people to find information quickly.",
        "Today the internet supports communication, education, business, and entertainment. People send messages, attend classes, shop, and watch videos from nearly anywhere.",
        "This power brings new challenges, including questions about privacy, the accuracy of information, and unequal access. Using the internet wisely means thinking carefully about both its benefits and its risks.",
        "Understanding how the internet works helps people become thoughtful, responsible users of one of history's most powerful tools."],
        questions: [
          ["What is the internet?", "A network linking billions of computers and devices", "A single computer", "A television channel", "A type of phone only"],
          ["When did the internet begin as a research project?", "The 1960s", "The 1990s", "The 1800s", "The year 2020"],
          ["What are the shared rules that let machines exchange data called?", "Protocols", "Passwords", "Cables", "Browsers"],
          ["How does information travel across the internet?", "In small packets along many paths", "In one large block on one path", "Only through the air", "By mail"],
          ["Why is the network hard to shut down completely?", "Data can travel many possible paths", "One company controls it", "It uses no rules", "It is very small"],
          ["What made the internet easy to use in the 1990s?", "The World Wide Web", "The steam engine", "The telegraph", "The printing press"],
          ["What tools help people find information online?", "Web browsers and search engines", "Typewriters", "Telescopes", "Compasses"],
          ["What are some challenges the internet brings?", "Privacy, accuracy, and unequal access", "Only faster computers", "No challenges at all", "Cheaper cables only"],
          ["What does using the internet wisely require?", "Thinking about benefits and risks", "Ignoring all risks", "Believing everything online", "Avoiding it entirely"],
          ["What is the author's main point?", "Understanding the internet helps people use it responsibly", "The internet has no risks", "Networks should be secret", "Computers cannot share data"]] },
      { title: "Vaccines and Modern Medicine", paragraphs: [
        "For most of history, infectious diseases such as smallpox and polio killed or disabled huge numbers of people. One of medicine's greatest achievements has been the development of vaccines to prevent many of these illnesses.",
        "A vaccine works by training the body's immune system. It exposes the body to a harmless piece or weakened form of a germ. The immune system learns to recognize that germ and prepares defenses, so if the real germ ever appears, the body can fight it off quickly.",
        "In 1796, Edward Jenner performed an early vaccination against smallpox. Over the following centuries, scientists developed vaccines against many diseases. Smallpox, once a deadly threat worldwide, was declared eradicated in 1980.",
        "When enough people in a community are vaccinated, diseases struggle to spread. This protection, sometimes called herd immunity, also shields people who cannot be vaccinated, such as newborns or those with certain illnesses.",
        "Modern medicine combines vaccines with clean water, better nutrition, and new treatments to help people live longer, healthier lives.",
        "Like all science, medicine advances through careful testing, evidence, and cooperation among researchers around the world."],
        questions: [
          ["What have vaccines helped prevent?", "Infectious diseases", "Earthquakes", "Bad weather", "Traffic jams"],
          ["How does a vaccine work?", "It trains the immune system to recognize a germ", "It replaces the blood", "It removes all germs from the air", "It cools the body"],
          ["What does a vaccine expose the body to?", "A harmless or weakened form of a germ", "A strong live disease", "A metal", "A vitamin only"],
          ["Who performed an early smallpox vaccination in 1796?", "Edward Jenner", "Isaac Newton", "Louis Pasteur", "Gregor Mendel"],
          ["What happened to smallpox by 1980?", "It was declared eradicated", "It became more common", "It was ignored", "It turned harmless on its own"],
          ["What is it called when enough people are vaccinated to slow a disease?", "Herd immunity", "Inertia", "Photosynthesis", "Erosion"],
          ["Who does herd immunity also help protect?", "People who cannot be vaccinated", "Only adults", "No one else", "Only doctors"],
          ["Besides vaccines, what helps people live longer?", "Clean water, nutrition, and new treatments", "Ignoring illness", "Less sleep", "Fewer doctors"],
          ["How does medicine advance?", "Through testing, evidence, and cooperation", "Through guessing", "By keeping secrets", "By avoiding research"],
          ["What is the main idea of the passage?", "Vaccines and modern medicine prevent disease and save lives", "Diseases cannot be prevented", "Vaccines cause all illness", "Medicine never changes"]] },
    ]},
    { name: "American History", stories: [
      { title: "The American Revolution", paragraphs: [
        "In the 1700s, Great Britain ruled thirteen colonies along the eastern coast of North America. Over time, many colonists grew angry that they were taxed by a distant government in which they had no representatives.",
        "The slogan 'no taxation without representation' captured their frustration. Protests, such as the Boston Tea Party, showed growing resistance. In 1775, fighting broke out between colonial militias and British troops.",
        "In 1776, the colonies adopted the Declaration of Independence, written mainly by Thomas Jefferson. It announced that the colonies were free and independent states and stated that people have rights that governments must protect.",
        "The war that followed was long and difficult. With leadership from George Washington and help from allies such as France, the Americans eventually defeated the British.",
        "The new United States then faced the challenge of building a government. The Revolution's ideas about liberty and self-government influenced people around the world.",
        "Understanding the Revolution helps explain the values and institutions of the United States today."],
        questions: [
          ["How many colonies did Britain rule in North America?", "Thirteen", "Fifty", "Three", "One hundred"],
          ["Why were many colonists angry?", "They were taxed without representation", "They had too much land", "They paid no taxes at all", "They had no farms"],
          ["What slogan captured colonists' frustration?", "No taxation without representation", "Give me liberty or give me tea", "All roads lead to Rome", "United we bake"],
          ["What protest showed growing resistance?", "The Boston Tea Party", "The Gold Rush", "The Louisiana Purchase", "The Great Migration"],
          ["When was the Declaration of Independence adopted?", "1776", "1492", "1865", "1969"],
          ["Who wrote most of the Declaration of Independence?", "Thomas Jefferson", "George Washington", "Benjamin Franklin", "Abraham Lincoln"],
          ["Who led the American forces in the war?", "George Washington", "Thomas Edison", "Ulysses S. Grant", "Paul Revere"],
          ["Which country helped the Americans as an ally?", "France", "Spain only", "Russia", "China"],
          ["What did the new United States face after the war?", "Building a government", "Nothing new", "Choosing a king", "Returning to Britain"],
          ["How did the Revolution's ideas affect the world?", "They influenced people's ideas about liberty and self-government", "They ended all wars", "They had no effect", "They applied only to Britain"]] },
      { title: "The U.S. Constitution", paragraphs: [
        "After winning independence, the United States needed a plan of government. Its first attempt, the Articles of Confederation, created a national government too weak to solve the country's problems.",
        "In 1787, delegates met in Philadelphia and wrote a new plan: the Constitution. It created a stronger national government while dividing power to prevent any one part from becoming too strong.",
        "The Constitution separates the government into three branches. The legislative branch, Congress, makes laws. The executive branch, led by the president, carries out laws. The judicial branch, the courts, interprets laws. A system of checks and balances lets each branch limit the others.",
        "To protect individual rights, the first ten amendments, called the Bill of Rights, were added. They guarantee freedoms such as speech, religion, and a fair trial.",
        "The Constitution can be amended, allowing it to change over time. It has guided the United States for more than two centuries and remains the country's supreme law.",
        "Studying the Constitution helps citizens understand their rights and how their government works."],
        questions: [
          ["What was the first plan of government called?", "The Articles of Confederation", "The Bill of Rights", "The Declaration", "The Magna Carta"],
          ["Why was the first plan replaced?", "It created a government too weak to solve problems", "It was too powerful", "It banned voting", "It had no writing"],
          ["When was the Constitution written?", "1787", "1620", "1865", "1945"],
          ["How many branches does the government have?", "Three", "One", "Two", "Five"],
          ["Which branch makes laws?", "The legislative branch (Congress)", "The executive branch", "The judicial branch", "The military"],
          ["Which branch carries out laws?", "The executive branch (the president)", "Congress", "The courts", "The states"],
          ["Which branch interprets laws?", "The judicial branch (the courts)", "Congress", "The president", "The army"],
          ["What lets each branch limit the others?", "Checks and balances", "A single ruler", "No rules", "The Bill of Rights only"],
          ["What are the first ten amendments called?", "The Bill of Rights", "The Preamble", "The Articles", "The Declaration"],
          ["Why can the Constitution stay relevant over time?", "It can be amended", "It never changes", "It is not a law", "It is secret"]] },
    ]},
    { name: "Economics & Society", stories: [
      { title: "Supply, Demand, and Markets", paragraphs: [
        "Every day, people buy and sell goods and services in markets. Two forces, supply and demand, work together to shape the prices we see.",
        "Demand is how much of a good buyers are willing to purchase, while supply is how much sellers are willing to provide. When many buyers want a product that is scarce, its price tends to rise. When sellers offer more than buyers want, prices tend to fall.",
        "Prices act as signals. A high price encourages sellers to produce more and buyers to look for alternatives. A low price does the opposite. Through countless individual choices, markets tend to move toward a price where the amount supplied roughly equals the amount demanded.",
        "Real markets are more complicated. Costs, competition, taxes, and world events all affect prices. Sometimes governments step in to protect consumers or workers.",
        "Understanding supply and demand helps people make sense of everyday prices, from groceries to gasoline, and helps citizens think about economic decisions.",
        "These ideas also help explain larger events, such as why prices rise during shortages or fall when a product becomes plentiful."],
        questions: [
          ["What two forces shape prices in a market?", "Supply and demand", "Wind and rain", "Time and space", "Heat and light"],
          ["What is demand?", "How much buyers are willing to purchase", "How much sellers provide", "The cost to make a good", "A type of tax"],
          ["What is supply?", "How much sellers are willing to provide", "How much buyers want", "The store's location", "The weather"],
          ["What happens when many buyers want a scarce product?", "Its price tends to rise", "Its price falls", "It disappears", "It becomes free"],
          ["What happens when sellers offer more than buyers want?", "Prices tend to fall", "Prices rise sharply", "Prices freeze forever", "The market closes"],
          ["What do prices act as?", "Signals for buyers and sellers", "Random numbers", "Government orders", "Fixed rules that never change"],
          ["Toward what price do markets tend to move?", "Where amount supplied roughly equals amount demanded", "The highest possible price", "Zero", "A price set by one buyer"],
          ["What else can affect real prices?", "Costs, competition, taxes, and world events", "Only the seller's mood", "Nothing else", "Only the color of the product"],
          ["Why might a government step into a market?", "To protect consumers or workers", "To raise all prices", "To close all stores", "To ban trade"],
          ["What is the main idea of the passage?", "Supply and demand help explain prices and economic events", "Prices never change", "Only sellers set prices", "Markets are simple and fixed"]] },
      { title: "The Industrial Revolution and the World of Work", paragraphs: [
        "The Industrial Revolution, which began in Britain in the late 1700s, transformed how goods were made. New machines powered by steam allowed factories to produce cloth, tools, and other products faster and more cheaply than ever before.",
        "As factories grew, people moved from farms and villages into rapidly expanding cities to find work. This shift changed family life, daily routines, and the landscape itself, as smokestacks rose above crowded neighborhoods.",
        "Factory work could be hard and dangerous. Long hours, low pay, and unsafe machines were common, and even young children labored in mills and mines. Over time, workers organized into groups called labor unions to demand better conditions.",
        "Reformers and governments eventually passed laws limiting child labor, shortening working hours, and improving safety. These changes came slowly and often followed years of struggle.",
        "The Industrial Revolution created enormous wealth and many new products, but it also raised lasting questions about fairness, working conditions, and the effects of industry on the environment.",
        "Its consequences \u2014 both the benefits and the problems \u2014 still shape economies and societies around the world today."],
        questions: [
          ["Where and when did the Industrial Revolution begin?", "Britain in the late 1700s", "Egypt in ancient times", "America in the 1900s", "China in the 1600s"],
          ["What powered the new factory machines?", "Steam", "Solar panels", "Wind turbines", "Electricity from the grid"],
          ["Why did people move into cities?", "To find work in factories", "To escape the rain", "To become farmers", "To avoid machines"],
          ["What was factory work often like?", "Hard and dangerous", "Easy and safe", "Short and well paid", "Rare and optional"],
          ["Who sometimes labored in mills and mines?", "Young children", "Only adults", "Only wealthy owners", "No one"],
          ["What did workers form to demand better conditions?", "Labor unions", "Sports teams", "Trading companies", "Armies"],
          ["What did reformers and governments eventually do?", "Passed laws limiting child labor and improving safety", "Banned all factories", "Raised child labor", "Ignored the problems"],
          ["How did these improvements usually come about?", "Slowly, after years of struggle", "Instantly and easily", "Without any effort", "By accident only"],
          ["What did the Industrial Revolution create besides wealth?", "Lasting questions about fairness and the environment", "Nothing new", "Only farms", "Fewer products"],
          ["What is the main idea of the passage?", "Industrialization brought both progress and serious problems", "Factories had no effect", "Everyone became rich equally", "Work became easy for all"]] },
    ]},
  ];

  global.ReadingMiddle = { "grade-6": GRADE6, "grade-7": GRADE7, "grade-8": GRADE8 };
})(window);
